# Generated by Django 4.0.1 on 2022-01-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, verbose_name='Username')),
                ('password', models.CharField(max_length=254, verbose_name='Senha')),
                ('firstname', models.CharField(max_length=254, verbose_name='Primeiro')),
                ('lastname', models.CharField(max_length=254, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('course1', models.CharField(max_length=254, verbose_name='Disciplina')),
            ],
        ),
    ]
